### ISSUE TITLE
Support text definition of visualization

### ISSUE THREAD

**Issue by Mogztter** [data2viz/data2viz#111]
The DSL is really clean but I think it could be useful, especially in documentation, to describe visualization as text.
My idea is to be able to define visualizations in text documents. For instance:

```adoc
= Visualization

.A Red Rectangle
[data2viz]
----
viz {
  width = 400.0
  height = 400.0
  rect {
    width = 50.0
    height = 50.0
    x = 100.0
    y = 100.0
    style.fill = "red"
  }
}
----
```

And when the document will be converted to HTML, the visualization will be rendered.
Is there any plan to add a text parser at some point to generate a visualization ?

**Comment by gzoritchak** [comment]
The choice of Kotlin as a language is partly due to its ability of creating nice DSLs. It allows to create visualization definitions that seems to be purely declarative but are, in fact, code. 

With text descriptions we would loose all the tooling features of the language. It will put a lot more work on our side to check the validity of the description. Currently, this comes for free with the compilation.

You can check that here: https://play.data2viz.io/tutorials/getting-started/

When editing the color, if you just start to type a letter, you have code completion using CTRL+SPACE
`fill = Colors.Web.red`

![image](https://user-images.githubusercontent.com/1110254/51827836-8d4f8000-22ea-11e9-9b66-3cb6ecb1afa5.png)

**Comment by Mogztter** [comment]
> The choice of Kotlin as a language is partly due to its ability of creating nice DSLs. It allows to create visualization definitions that seems to be purely declarative but are, in fact, code.

I get it and indeed the DSL is extremely powerful.

> With text descriptions we would loose all the tooling features of the language. It will put a lot more work on our side to check the validity of the description. Currently, this comes for free with the compilation.
You can check that here: https://play.data2viz.io/tutorials/getting-started/

The getting started guide is really neat, well done :ok_hand: 
As far as I understand, it sends the Kotlin code to a compiler server (https://compile.data2viz.io/kotlinServer) and it returns the code compiled to JavaScript right ? Is the "compiler server" an Open Source project ?

I guess I could automatically wrap the diagram definition (ie. infer then render method and the imports). So instead of sending:

```kotlin
import io.data2viz.color.*		
import io.data2viz.geom.*
import io.data2viz.viz.*

fun main() {								
    viz {										
        size = size(200, 50)				    
        rect {								
            size = size(50, 50)
            fill = Colors.Web.blueviolet
        }
    }.bindRendererOnNewCanvas()
}
```

A user could just send:

```
viz {										
  size = size(200, 50)				    
  rect {								
    size = size(50, 50)
    fill = Colors.Web.blueviolet
  }
}
```

Ideally the response should be an svg image (but I think it's already possible https://data2viz.github.io/data2viz/ex-force-js/index.html Olympic rings :heart_eyes: ).

My goal is to give a text description (arguably code is also a text description) and get an image. I think it would opens up a lot of possibilities because you can then use it everywhere. But with the Kotlin compiler we are almost there :wink: 

Anyway thanks for the pointer.
