### ISSUE TITLE
Unclear Concept of Mouse-Events

### ISSUE THREAD

**Issue by dnltsk** [data2viz/data2viz#185]
I'm trying to start a project based on data2viz. Now I'm unable to select act do some action with a selected element.

Given the following modification of the barchart example from https://github.com/data2viz/data2viz-examples/blob/master/tutorials/barchart-js/src/main/kotlin/MainJS.kt

```
        rect {
          width = xScale(datum)
          height = barHeight
          fill = Colors.Web.steelblue

          on(KMouseDown) { event ->
            println("KMouseDown $event")
            // how to select clicked element to modify it?
          }
        }
```

Actually, my expectation is that the click-event event is only triggert by clicking on a rectangle, instead it gets triggert when I click somewhere on the whole canvas.

In the next step I want change the color of the clicked rectangle. But I haven't found a way to get the clicked instance.

I think that the World Temperature example is a great starting point
https://play.data2viz.io/pierre/sketches/wYqPKL/edit/

But the two steps described above are not covered there, unfortunately.

Can you explain me how to work with mouse events on geometry level?

**Comment by gzoritchak** [comment]
Currently, we only add event listeners on the visualization. Your code is valid because the `rect` lambda is inside the visualization. So you are calling `Viz.on` and not `RectNode.on` as you are expecting.

We plan to provide this event listeners on the basic geometric elements, but it isn't straightforward. As we are using canvas to render all the graphics elements, we need to calculate the position of each element to be able to do this. There is no underlying component like SVG that natively handles the events. We'll also need to implement transformation composition to manage the element position after some group translation or rotation.
